In [1]:
import numpy as np

In [2]:
arr = np.arange(1, 16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Wybór elementu po indeksie

In [3]:
arr[2]

3

In [4]:
arr[2:5]

array([3, 4, 5])

In [5]:
arr[:8]

array([1, 2, 3, 4, 5, 6, 7, 8])

Przypisywanie nowej wartości

In [6]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [8]:
arr[0] = 100
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15])

In [9]:
arr[10:12] = 200
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10, 200, 200,  13,
        14,  15])

Zmiana kształtu

In [10]:
arr = np.arange(1, 16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [11]:
arr2d = arr.reshape(3, 5)
arr2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

Maski logiczne

In [12]:
arr_rnd = np.random.randn(3, 5)
arr_rnd

array([[-2.37527244e-01, -5.63450975e-01,  8.20710716e-01,
        -8.31329377e-01,  4.07670962e-01],
       [-1.58254844e+00,  8.43844763e-01,  1.32187942e+00,
         9.04040699e-01,  1.30174040e-01],
       [ 1.55281380e-01, -1.90207899e-01,  2.08347870e-01,
        -1.53412579e-01, -1.37413754e-03]])

In [13]:
arr_bool = arr_rnd > 0
arr_bool

array([[False, False,  True, False,  True],
       [False,  True,  True,  True,  True],
       [ True, False,  True, False, False]])

In [14]:
arr_rnd[arr_bool]

array([0.82071072, 0.40767096, 0.84384476, 1.32187942, 0.9040407 ,
       0.13017404, 0.15528138, 0.20834787])

In [15]:
arr_rnd[arr_rnd > 0]

array([0.82071072, 0.40767096, 0.84384476, 1.32187942, 0.9040407 ,
       0.13017404, 0.15528138, 0.20834787])

In [16]:
arr_rnd[arr_rnd < 0]

array([-2.37527244e-01, -5.63450975e-01, -8.31329377e-01, -1.58254844e+00,
       -1.90207899e-01, -1.53412579e-01, -1.37413754e-03])